<?php

$v[''] = array(
		'script' = array(
			'say liuyue at 0.58 for 0.41 speak gang cai ',
			'say liuyue at 1.61 for 1.33 speak wo men zhuo zhong fen xi le krap ',
			'say liuyue at 3.43 for 0.34 speak asshol ',
			'say liuyue at 4.67 for 2.38 speak zhei xie wei mei guo da zhong suo xi wen le jian de ',
			'say liuyue at 8.53 for 0.72 speak guan yu meik lov ',
			'say liuyue at 9.53 for 1.13 speak nat workraft zhei ji gu ',
			'say liuyue at 11.61 for 2.36 speak wo men xia mian lai jian dan jie shao yi xia hou mian ',
			'say liuyue at 15.42 for 0.99 speak you xing qu de peng you ',
			'say liuyue at 17.04 for 1.74 speak ke yi sui hou guan kan dai zi mu de ban ',
			'say liuyue at 19.57 for 0.49 speak lai liao jie zheng ',
			'say liuyue at 20.28 for 0.4 speak geer de gu shi ',
			'say liuyue at 21.97 for 0.3 speak ling wai ',
			'say liuyue at 23.12 for 1.01 speak guan yu ying yu xue xi ',
			'say liuyue at 25.13 for 1.35 speak wo de jing yan he zhu zhang shi ',
			'say liuyue at 27.24 for 1.53 speak jin liang zhao dao zi ji zhen zheng gan ',
			'say liuyue at 29 for 0.37 speak xing qu de dong ',
			'say liuyue at 30.66 for 0.79 speak xi huan wan you xi ne ',
			'say liuyue at 32.26 for 1.32 speak ni jiu shao wan ka ding che jin wu ',
			'say liuyue at 33.85 for 0.11 speak tuan ',
			'say liuyue at 34.84 for 1.54 speak duo wan ying wen ban de zui zhong huan xiang ',
			'say liuyue at 36.61 for 0.24 speak shen me de ',
			'say liuyue at 37.92 for 0.67 speak xi huan ting ge ne ',
			'say liuyue at 39.29 for 1.21 speak ni jiu shao ting dian zhuo jie lun ',
			'say liuyue at 40.9 for 0.79 speak duo ting dian eminem ',
			'say liuyue at 43 for 0.87 speak xi huan kan dian shi ju ne ',
			'say liuyue at 44.59 for 1.29 speak ni jiu shao kan dian tian long ba bu ',
			'say liuyue at 46.41 for 1.14 speak duo kan dian nan fang gong yuan ',
			'say liuyue at 48.68 for 0.94 speak xi huan kan dian ying ne ',
			'say liuyue at 50.42 for 1.18 speak ni jiu shao kan dian feng xiao gang ',
			'say liuyue at 52.06 for 0.77 speak duo kan dian hao lai wu ',
			'say liuyue at 54.07 for 1.96 speak zhei ge kan dian shi ting ge wan you xi ',
			'say liuyue at 56.6 for 0.69 speak fei chang ji hui ',
			'say liuyue at 57.64 for 0.2 speak fan yi ',
			'say liuyue at 58.73 for 0.83 speak you shen me bu ming bai ',
			'say liuyue at 59.84 for 1.38 speak jiu zhi jie qu zhao ying wen zi liao ',
			'say liuyue at 61.86 for 0.55 speak zhei yang de hua ',
			'say liuyue at 63.08 for 0.72 speak zi ran jiu ke yi xue hao ',
			'say liuyue at 65.55 for 1.69 speak shang xin dong fang shan mu pei xun shen me de ',
			'say liuyue at 68.15 for 1.09 speak bu neng shuo pi yong mei you ',
			'say liuyue at 69.97 for 0.83 speak dan shi bu xu ji zhu ',
			'say liuyue at 71.69 for 1.83 speak jian shi wu lun duo you ren ge mei li ',
			'say liuyue at 74.3 for 1.64 speak duo me feng qu you mo yu jiao yu le ',
			'say liuyue at 76.61 for 0.35 speak nei ge ya ',
			'say liuyue at 77.65 for 0.56 speak shi ta de dong xi ',
			'say liuyue at 79 for 0.25 speak bu shi ni ',
			'say liuyue at 80.7 for 1.4 speak yao ti gao zi ji de shui ping ',
			'say liuyue at 82.7 for 0.58 speak hai shi yao zi ji ',
			'say liuyue at 83.55 for 0.14 speak xia ',
			'say liuyue at 85.64 for 0.75 speak zhei wei shuo le ',
			'say liuyue at 87.24 for 1.21 speak na wo kan yi jia jiang tan ga ma ',
			'say liuyue at 89.65 for 0.38 speak qi shi ',
			'say liuyue at 90.53 for 0.93 speak wo ye jiu shi xi wang a ',
			'say liuyue at 92.31 for 2.41 speak tong guo jie shao yi xie wo jue de you yi si de dong xi ',
			'say liuyue at 95.52 for 0.95 speak lai diao dong qi nin ne ',
			'say liuyue at 97.11 for 0.84 speak duo zhei xie dong xi de xing qu ',
			'say liuyue at 99.24 for 1.14 speak zhen xin xi wang ge wei ',
			'say liuyue at 100.76 for 0.88 speak neng xi huan yi jia jiang ',
			'say liuyue at 101.92 for 1 speak tan zhei ge jie mu de nei rong ',
			'say liuyue at 103.81 for 0.21 speak xia mian ',
			),		'name' => '');

?>