<?

$index_scene = 1;
$v['scene_00001'] = array(
		'duration'	=> 106,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 104 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_19 104 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.58 for 0.41 speak gang cai ',
			'say liuyue at 1.61 for 1.33 speak wo men zhuo zhong fen xi le krap ',
			'say liuyue at 3.43 for 0.34 speak asshol ',
			'say liuyue at 4.67 for 2.38 speak zhei xie wei mei guo da zhong suo xi wen le jian de ',
			'say liuyue at 8.53 for 0.72 speak guan yu meik lov ',
			'say liuyue at 9.53 for 1.13 speak nat workraft zhei ji gu ',
			'say liuyue at 11.61 for 2.36 speak wo men xia mian lai jian dan jie shao yi xia hou mian ',
			'say liuyue at 15.42 for 0.99 speak you xing qu de peng you ',
			'say liuyue at 17.04 for 1.74 speak ke yi sui hou guan kan dai zi mu de ban ',
			'say liuyue at 19.57 for 0.49 speak lai liao jie zheng ',
			'say liuyue at 20.28 for 0.4 speak geer de gu shi ',
			'say liuyue at 21.97 for 0.3 speak ling wai ',
			'say liuyue at 23.12 for 1.01 speak guan yu ying yu xue xi ',
			'say liuyue at 25.13 for 1.35 speak wo de jing yan he zhu zhang shi ',
			'say liuyue at 27.24 for 1.53 speak jin liang zhao dao zi ji zhen zheng gan ',
			'say liuyue at 29 for 0.37 speak xing qu de dong ',
			'say liuyue at 30.66 for 0.79 speak xi huan wan you xi ne ',
			'say liuyue at 32.26 for 1.32 speak ni jiu shao wan ka ding che jin wu ',
			'say liuyue at 33.85 for 0.11 speak tuan ',
			'say liuyue at 34.84 for 1.54 speak duo wan ying wen ban de zui zhong huan xiang ',
			'say liuyue at 36.61 for 0.24 speak shen me de ',
			'say liuyue at 37.92 for 0.67 speak xi huan ting ge ne ',
			'say liuyue at 39.29 for 1.21 speak ni jiu shao ting dian zhuo jie lun ',
			'say liuyue at 40.9 for 0.79 speak duo ting dian eminem ',
			'say liuyue at 43 for 0.87 speak xi huan kan dian shi ju ne ',
			'say liuyue at 44.59 for 1.29 speak ni jiu shao kan dian tian long ba bu ',
			'say liuyue at 46.41 for 1.14 speak duo kan dian nan fang gong yuan ',
			'say liuyue at 48.68 for 0.94 speak xi huan kan dian ying ne ',
			'say liuyue at 50.42 for 1.18 speak ni jiu shao kan dian feng xiao gang ',
			'say liuyue at 52.06 for 0.77 speak duo kan dian hao lai wu ',
			'say liuyue at 54.07 for 1.96 speak zhei ge kan dian shi ting ge wan you xi ',
			'say liuyue at 56.6 for 0.69 speak fei chang ji hui ',
			'say liuyue at 57.64 for 0.2 speak fan yi ',
			'say liuyue at 58.73 for 0.83 speak you shen me bu ming bai ',
			'say liuyue at 59.84 for 1.38 speak jiu zhi jie qu zhao ying wen zi liao ',
			'say liuyue at 61.86 for 0.55 speak zhei yang de hua ',
			'say liuyue at 63.08 for 0.72 speak zi ran jiu ke yi xue hao ',
			'say liuyue at 65.55 for 1.69 speak shang xin dong fang shan mu pei xun shen me de ',
			'say liuyue at 68.15 for 1.09 speak bu neng shuo pi yong mei you ',
			'say liuyue at 69.97 for 0.83 speak dan shi bu xu ji zhu ',
			'say liuyue at 71.69 for 1.83 speak jian shi wu lun duo you ren ge mei li ',
			'say liuyue at 74.3 for 1.64 speak duo me feng qu you mo yu jiao yu le ',
			'say liuyue at 76.61 for 0.35 speak nei ge ya ',
			'say liuyue at 77.65 for 0.56 speak shi ta de dong xi ',
			'say liuyue at 79 for 0.25 speak bu shi ni ',
			'say liuyue at 80.7 for 1.4 speak yao ti gao zi ji de shui ping ',
			'say liuyue at 82.7 for 0.58 speak hai shi yao zi ji ',
			'say liuyue at 83.55 for 0.14 speak xia ',
			'say liuyue at 85.64 for 0.75 speak zhei wei shuo le ',
			'say liuyue at 87.24 for 1.21 speak na wo kan yi jia jiang tan ga ma ',
			'say liuyue at 89.65 for 0.38 speak qi shi ',
			'say liuyue at 90.53 for 0.93 speak wo ye jiu shi xi wang a ',
			'say liuyue at 92.31 for 2.41 speak tong guo jie shao yi xie wo jue de you yi si de dong xi ',
			'say liuyue at 95.52 for 0.95 speak lai diao dong qi nin ne ',
			'say liuyue at 97.11 for 0.84 speak duo zhei xie dong xi de xing qu ',
			'say liuyue at 99.24 for 1.14 speak zhen xin xi wang ge wei ',
			'say liuyue at 100.76 for 0.88 speak neng xi huan yi jia jiang ',
			'say liuyue at 101.92 for 1 speak tan zhei ge jie mu de nei rong ',
			'say liuyue at 103.81 for 0.21 speak xia mian ',
			),
		'name'		=> 'Scene ');

$v['scene_00002'] = $v['scene_00001'];
$v['scene_00002']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00003'] = $v['scene_00001'];
$v['scene_00003']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00004'] = $v['scene_00001'];
$v['scene_00004']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00005'] = array(
		'duration'	=> 15,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 13 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_20 13 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.5 for 1.51 speak you xi zhi zuo zhe de tai du hen wu nai ',
			'say liuyue at 3.11 for 1.73 speak wei shen me yao sha si wu gu de wan jia ne ',
			'say liuyue at 5.78 for 1.68 speak zhei ge you xi de mu di shi wan cheng ren wu a ',
			'say liuyue at 9.44 for 1 speak zhei ju hua bei hou yin ',
			'say liuyue at 10.72 for 0.89 speak cang zhe hei shen de zhe li ',
			'say liuyue at 13.14 for 0.12 speak hui ',
			),
		'name'		=> 'Scene ');

$v['scene_00006'] = $v['scene_00005'];
$v['scene_00006']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00007'] = $v['scene_00005'];
$v['scene_00007']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00008'] = $v['scene_00005'];
$v['scene_00008']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00009'] = array(
		'duration'	=> 22,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 20 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_21 20 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.54 for 1.04 speak zhim shuo wo dei hui jia ',
			'say liuyue at 2.35 for 1.62 speak wo de hai zi men zheng wan mo shou shi jie ne ',
			'say liuyue at 4.88 for 0.2 speak ling dao ',
			'say liuyue at 5.58 for 0.36 speak gao su ta ',
			'say liuyue at 6.95 for 0.83 speak ni hai zi de ren wu ',
			'say liuyue at 8.05 for 0.12 speak yi jing bei ',
			'say liuyue at 10.01 for 1.09 speak zhim jue wang di jiao dao ',
			'say liuyue at 11.56 for 0.18 speak bu ',
			'say liuyue at 12.28 for 1.52 speak ta men de you xi cai gang gang kai shi ',
			'say liuyue at 15.03 for 0.33 speak zhei duan ',
			'say liuyue at 15.81 for 1.72 speak shi dian xing de hun tong you xi he xian shi ',
			'say liuyue at 18.35 for 0.4 speak lai da dao gao ',
			'say liuyue at 18.97 for 0.13 speak xiao de ',
			'say liuyue at 20.23 for 1.36 speak zhei ji nan fang gong yuan li duo ci ',
			),
		'name'		=> 'Scene ');

$v['scene_00010'] = $v['scene_00009'];
$v['scene_00010']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00011'] = $v['scene_00009'];
$v['scene_00011']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00012'] = $v['scene_00009'];
$v['scene_00012']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00013'] = array(
		'duration'	=> 26,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 24 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_22 24 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.47 for 1.44 speak zhei ji hua zhi yi guo lai shi ',
			'say liuyue at 3.03 for 3.19 speak wo men yao dui fu de jia huo o wan wan quan quan mei you ',
			'say liuyue at 6.49 for 0.29 speak sheng ming ',
			'say liuyue at 7.83 for 1.74 speak zha kan qi lai you dian rang ren mo bu zhao tou nao ',
			'say liuyue at 10.57 for 0.93 speak hav no laif bu jiu ',
			'say liuyue at 11.85 for 0.2 speak si le ma ',
			'say liuyue at 12.65 for 0.42 speak shi shen me yi si ',
			'say liuyue at 14.13 for 0.32 speak qi shi ',
			'say liuyue at 15.16 for 0.31 speak zhei ge ',
			'say liuyue at 15.98 for 0.7 speak shi da jia dui ',
			'say liuyue at 16.93 for 1.23 speak tong yi zhong shi wu de bu tong jiao ',
			'say liuyue at 19.18 for 0.37 speak zai ri ben ',
			'say liuyue at 20.29 for 0.85 speak zhei jiu jiao zhai nan ',
			'say liuyue at 21.82 for 0.62 speak zai zhong guo ne ',
			'say liuyue at 23.05 for 0.49 speak jiu jiao zuo ',
			'say liuyue at 24.02 for 0.86 speak dian zi hai luo yin ',
			),
		'name'		=> 'Scene ');

$v['scene_00014'] = $v['scene_00013'];
$v['scene_00014']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00015'] = $v['scene_00013'];
$v['scene_00015']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00016'] = $v['scene_00013'];
$v['scene_00016']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00017'] = array(
		'duration'	=> 34,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 32 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_23 32 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.35 for 1.15 speak klaid yao da tui tang gu ',
			'say liuyue at 2.37 for 1.04 speak katman ji li ta shuo ',
			'say liuyue at 4.25 for 1.64 speak ru guo ni xian zai yao shi you ge ji hui ',
			'say liuyue at 6.38 for 0.98 speak hui dao tuo qu zu zhi ',
			'say liuyue at 7.6 for 0.41 speak xi te le ',
			'say liuyue at 8.39 for 0.57 speak ni hui bu hui qu ',
			'say liuyue at 10.47 for 1.47 speak ran hou ta ting le yi xia ',
			'say liuyue at 13.05 for 1.01 speak shuo wo de yi si shi ',
			'say liuyue at 14.48 for 0.15 speak jiu wo ',
			'say liuyue at 14.86 for 1.09 speak ge ren er yan wo bu hui ',
			'say liuyue at 16.35 for 0.99 speak yin wei wo chong bai xi te le ',
			'say liuyue at 17.75 for 0.22 speak dan shi ni ',
			'say liuyue at 18.19 for 0.5 speak hui dui bu dui ',
			'say liuyue at 20.12 for 0.86 speak zhei ge di fang bi jiao gao ',
			'say liuyue at 22.52 for 0.91 speak ling wai shun bian shuo yi ju ',
			'say liuyue at 24.12 for 0.68 speak zai she ding li ',
			'say liuyue at 25.02 for 0.3 speak katman ',
			'say liuyue at 25.59 for 0.93 speak te tao yan you tai ren ',
			'say liuyue at 27.47 for 0.37 speak zhei ge ',
			'say liuyue at 28.15 for 1.86 speak nan fang gong yuan li po ju jiang xin de yi ge she ding ',
			'say liuyue at 30.92 for 0.53 speak yin wei zhi zuo ren ',
			'say liuyue at 31.71 for 1.01 speak zhi yi mat sdon ',
			'say liuyue at 33.02 for 0.26 speak you tai ren ',
			),
		'name'		=> 'Scene ');

$v['scene_00018'] = $v['scene_00017'];
$v['scene_00018']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00019'] = $v['scene_00017'];
$v['scene_00019']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00020'] = $v['scene_00017'];
$v['scene_00020']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00021'] = array(
		'duration'	=> 14,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 12 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_24 12 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.75 for 2.93 speak zhei ju fa yu cheng jie shang wen wen klaid shi bu shi fa guo ren ',
			'say liuyue at 4.48 for 0.8 speak ta de yi si shi ',
			'say liuyue at 5.93 for 0.44 speak wil you ',
			'say liuyue at 6.59 for 0.61 speak slip wis me ',
			'say liuyue at 8.68 for 0.76 speak hao xiang shi ge ge ming ',
			'say liuyue at 10.06 for 1.09 speak bu guo wo bu tai dong fa yu ',
			'say liuyue at 11.71 for 0.78 speak suo yi yi ban bu ting ',
			),
		'name'		=> 'Scene ');

$v['scene_00022'] = $v['scene_00021'];
$v['scene_00022']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00023'] = $v['scene_00021'];
$v['scene_00023']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00024'] = $v['scene_00021'];
$v['scene_00024']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00025'] = array(
		'duration'	=> 15,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 13 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_25 13 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.71 for 1.32 speak katman bai zhao ji le bai tian ',
			'say liuyue at 2.89 for 1.54 speak qi shi gang cai chang fan diao de klaid ',
			'say liuyue at 5.18 for 1.53 speak zhen zai kan yi ben jiao zuo plei boi de za ',
			'say liuyue at 8.1 for 1.08 speak zhei za zhi wo mei kan guo ',
			'say liuyue at 10.08 for 3.16 speak kan ming zi ke neng shi jiao shao nan sheng wan de you xi shen ',
			),
		'name'		=> 'Scene ');

$v['scene_00026'] = $v['scene_00025'];
$v['scene_00026']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00027'] = $v['scene_00025'];
$v['scene_00027']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00028'] = $v['scene_00025'];
$v['scene_00028']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00029'] = array(
		'duration'	=> 20,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 18 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_26 18 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.36 for 0.95 speak zhei ju hua shi ge da chuan qi ',
			'say liuyue at 2.58 for 0.27 speak di xiong men ',
			'say liuyue at 3.72 for 1.7 speak dang xing shi bu rong le guan de shi hou ',
			'say liuyue at 6.14 for 2.42 speak ni men bu neng jiu zhe me fang qi zheng ge werld ',
			'say liuyue at 10.09 for 0.8 speak of workraft ya ',
			'say liuyue at 12.47 for 2.32 speak yin wei ying wen shi xian shuo shi jie hou shuo mo shou ',
			'say liuyue at 15.44 for 1.21 speak suo yi zhe ge di fang you dian gao xiao ',
			'say liuyue at 17.14 for 0.29 speak bu guo ne ',
			'say liuyue at 17.69 for 0.15 speak bu tai hao ',
			'say liuyue at 18.09 for 0.16 speak fan yi ',
			),
		'name'		=> 'Scene ');

$v['scene_00030'] = $v['scene_00029'];
$v['scene_00030']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00031'] = $v['scene_00029'];
$v['scene_00031']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00032'] = $v['scene_00029'];
$v['scene_00032']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00033'] = array(
		'duration'	=> 33,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 31 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_27 31 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.57 for 1.22 speak katman jing guo yi fan ji suan ',
			'say liuyue at 2.46 for 0.33 speak zhi chu ',
			'say liuyue at 3.47 for 1.53 speak ru guo mei tian zhi shui san ge xiao ',
			'say liuyue at 5.22 for 0.27 speak shi de hua ',
			'say liuyue at 6.37 for 1.75 speak tong guo sha di deng ji de guai wu ye zhu ',
			'say liuyue at 9 for 0.33 speak xu yao ',
			'say liuyue at 9.63 for 0.8 speak san ge xing qi ',
			'say liuyue at 10.72 for 1.64 speak wu tian shi san xiao shi er shi fen zhong ',
			'say liuyue at 13.03 for 1.07 speak jiu ke yi da dao san shi ji ',
			'say liuyue at 15.14 for 1.87 speak cong er suo xiao he bian tai jia mian zhi jian de ',
			'say liuyue at 18.36 for 0.26 speak ran hou ',
			'say liuyue at 19.19 for 1.84 speak ta you yi ci zhan xian chu zhuo yue de shan dong neng ',
			'say liuyue at 22.31 for 0.61 speak ni men yao zen me zuo ',
			'say liuyue at 24.09 for 2.29 speak ni men ke yi zai tai yang di xia zheng tian wan yi ge po qiu ',
			'say liuyue at 27.19 for 0.75 speak huo zhe e ',
			'say liuyue at 28.91 for 1.03 speak ni men ke yi zuo zai dian nao qian ',
			'say liuyue at 30.23 for 1.79 speak an zuo chu yi fan shi ye ',
			),
		'name'		=> 'Scene ');

$v['scene_00034'] = $v['scene_00033'];
$v['scene_00034']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00035'] = $v['scene_00033'];
$v['scene_00035']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00036'] = $v['scene_00033'];
$v['scene_00036']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));
$v['scene_00037'] = array(
		'duration'	=> 38,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 36 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_28 36 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.36 for 1.14 speak guan yu zhei ji nan fang gong yuaner ',
			'say liuyue at 1.97 for 0.77 speak wo men jiu jie shao dao zhei li ',
			'say liuyue at 3.76 for 1.34 speak gu shi zhen zheng de jie ju shi ',
			'say liuyue at 5.87 for 3.58 speak zhu jue men shi yong bei feng yin zai you pan zhong de yi qian ge zhen li zhi jian ',
			'say liuyue at 10.31 for 1.34 speak he li ji bai le bian tai jia mian ',
			'say liuyue at 12.14 for 1.25 speak wei hu le mo shou shi jie de he ping ',
			'say liuyue at 14.73 for 2.17 speak da jia ke yi qu chao ji yi shu gong zuo shi de bo ke ',
			'say liuyue at 17.52 for 1.74 speak guan kan wan zheng ban ben de meik lav ',
			'say liuyue at 19.48 for 0.53 speak nat workraft ',
			'say liuyue at 20.8 for 0.85 speak shi pin ju ben dou you ',
			'say liuyue at 22.91 for 1.65 speak wo ge ren tui jian mei you zi mu de ban ben ',
			'say liuyue at 25.5 for 1 speak jie he ying wen ju ben yi qi ',
			'say liuyue at 27.51 for 1.11 speak dui xue xi ying yu bang zhu ',
			'say liuyue at 30.66 for 0.12 speak hao ',
			'say liuyue at 31.83 for 0.92 speak zhei ji yi jia jiang ',
			'say liuyue at 33.02 for 0.63 speak tao jiu dao zhei li ',
			'say liuyue at 34.48 for 0.27 speak zan men ',
			'say liuyue at 35 for 0.2 speak xia ',
			'say liuyue at 35.49 for 0.3 speak xing qi zai ',
			),
		'name'		=> 'Scene ');

$v['scene_00038'] = $v['scene_00037'];
$v['scene_00038']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00039'] = $v['scene_00037'];
$v['scene_00039']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00040'] = $v['scene_00037'];
$v['scene_00040']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

?>