<?php

$index_scene = 1;

$v['scene_00001'] = array(
		'duration'	=> 51,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			//	'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			//	'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			//	'blend item_oneman_light at 49 for 1 from 0 to 100 ',
			//	'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_09 49 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.2 for 1.17 speak xia mian zhei duaner bi jiao chang ',
			'say liuyue at 3.48 for 1.38 speak wo o shi shuo xia mian zhei duan ying ',
			'say liuyue at 5.11 for 0.24 speak pian bi jiao ',
			'say liuyue at 7.08 for 1.18 speak wo xian da gai jie shao yi xia nei rong ',
			'say liuyue at 9.41 for 1.39 speak shuo xiao peng you men yi kuaier waner you xi ',
			'say liuyue at 11.63 for 1 speak tu ran beng chu yi ge ren lai ',
			'say liuyue at 13.44 for 1 speak mo fang maikou zhaiksen ',
			'say liuyue at 14.75 for 0.13 speak zuo le ',
			'say liuyue at 15.14 for 0.42 speak ji ge zao xing ',
			'say liuyue at 16.28 for 1.57 speak ran hou wu shi pi kei gui ze ',
			'say liuyue at 18.55 for 1.26 speak men yong de you xi ren wu sha ',
			'say liuyue at 21.25 for 1.17 speak zhei ge waner wang luo you xi ya ',
			'say liuyue at 23.13 for 1.29 speak you qi shi am am o ar pi zhi ',
			'say liuyue at 25.4 for 1.34 speak ta yi ban dou you suo wei de pi kei ',
			'say liuyue at 27.64 for 0.99 speak ye jiu shi pleier kill ',
			'say liuyue at 29.39 for 1.25 speak ye you ren shuo shi pleier killing ',
			'say liuyue at 31.5 for 1.78 speak zhe ge suo wei waner jia zhi jian hu xiang zhan dou ',
			'say liuyue at 34.82 for 1.39 speak bi ru zhei ge world of worcraft ',
			'say liuyue at 37.07 for 0.78 speak jiu xiang kail shuo de ',
			'say liuyue at 38.58 for 1.09 speak wo bu tong yi pi kei de hua ',
			'say liuyue at 40.08 for 0.55 speak bu neng sui bian ',
			'say liuyue at 41.97 for 0.43 speak dan shi ne ',
			'say liuyue at 42.92 for 0.41 speak zai zhei li ',
			'say liuyue at 43.99 for 1.41 speak nan fang gong yuaner de ju qing tian ma ',
			'say liuyue at 45.65 for 0.24 speak xing kong ',
			'say liuyue at 46.35 for 0.16 speak ei ',
			'say liuyue at 47.11 for 0.87 speak rang ren chu hu yi liao ',
			'say liuyue at 48.83 for 0.61 speak zan men lai kan zhei duan ying ',
			),
		'name'		=> 'Scene ');

$v['scene_00002'] = $v['scene_00001'];
$v['scene_00002']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00003'] = $v['scene_00001'];
$v['scene_00003']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00004'] = $v['scene_00001'];
$v['scene_00004']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00005'] = array(
		'duration'	=> 77,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 75 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_09 75 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.85 for 0.72 speak sdan wen qu naer ',
			'say liuyue at 2.12 for 1.1 speak kail gao ta shuo lai wo zheer ',
			'say liuyue at 4.07 for 0.48 speak ran hou ne ',
			'say liuyue at 5.18 for 1.42 speak kaitman bai chu lao da de zi tai ',
			'say liuyue at 7.14 for 0.85 speak ran hou ta shuo le yi ju ',
			'say liuyue at 8.71 for 2.19 speak ai am de maitiist dorf in all of azieros ',
			'say liuyue at 12.3 for 0.93 speak ju wo ge ren guan cha ',
			'say liuyue at 14.09 for 1.68 speak guo nei xue xiao li shuo ying wen li biao ',
			'say liuyue at 16.04 for 0.5 speak shi niu bi de ',
			'say liuyue at 17.49 for 0.99 speak bu tai chang ti dao maiti ',
			'say liuyue at 19.44 for 0.6 speak qi shi zhei ge cier ting ',
			'say liuyue at 20.4 for 0.12 speak yong ',
			'say liuyue at 21.6 for 1.42 speak ta de ming ci mait biao shi li liang ',
			'say liuyue at 23.97 for 2.07 speak zhu yi he mei de guo qu shi pin fa shi xiang tong de ',
			'say liuyue at 26.95 for 1.66 speak xxing rong ci maiti ne biao shi you li liang ',
			'say liuyue at 29.3 for 0.7 speak ye jiu shi niu bi ya ',
			'say liuyue at 31.07 for 1.47 speak zhei li shi zui gao ji maitiist ',
			'say liuyue at 33.48 for 0.37 speak wai jie wei ',
			'say liuyue at 34.22 for 1.34 speak bian wai wei ai jia yi es ',
			'say liuyue at 37.07 for 0.69 speak hou mian de zhei ge dorf ',
			'say liuyue at 38.21 for 0.83 speak shuo jian dan ye jian dan ',
			'say liuyue at 39.71 for 0.73 speak ru da jia suo jian ',
			'say liuyue at 41.02 for 0.11 speak jiu shi ai ',
			'say liuyue at 41.45 for 0.14 speak rener ',
			'say liuyue at 42.36 for 1.3 speak ye you ren fan yi cheng zhu ru ',
			'say liuyue at 44.58 for 0.6 speak shuo ma fan ne ye ',
			'say liuyue at 45.47 for 0.18 speak ma fan ',
			'say liuyue at 46.46 for 1.17 speak yao shuo qing chu ai rener dorf ',
			'say liuyue at 48.37 for 0.66 speak di jing goblin ',
			'say liuyue at 49.81 for 0.51 speak jing ling elf ',
			'say liuyue at 51.14 for 0.96 speak zhei xie qi huan wen xue li ',
			'say liuyue at 52.32 for 0.74 speak xia zuo mo chu lai de ',
			'say liuyue at 54.09 for 1.36 speak yi shi ban huier kong pa mei faer jiang ',
			'say liuyue at 56.58 for 1.18 speak geng bie ti gao deng jing ling ',
			'say liuyue at 58 for 0.28 speak hai elf ',
			'say liuyue at 59.05 for 0.56 speak an ye jing ling ',
			'say liuyue at 59.85 for 0.37 speak nait elf ',
			'say liuyue at 61.18 for 0.87 speak xie jing ling blad elf ',
			'say liuyue at 62.75 for 1.25 speak zhei xie worcraft li chu xian de dong xi ',
			'say liuyue at 65.06 for 0.35 speak bu guang shi zhong ',
			'say liuyue at 65.63 for 0.12 speak zu ',
			'say liuyue at 66.37 for 0.55 speak xiang azeros ',
			'say liuyue at 67.33 for 0.47 speak jiu shi ',
			'say liuyue at 68.06 for 0.86 speak mo shou shi jie de ',
			'say liuyue at 69.19 for 0.88 speak yi ge da lu de ming ',
			'say liuyue at 71.18 for 0.36 speak ke yi shuo ',
			'say liuyue at 72.05 for 0.97 speak world of worcraft ',
			'say liuyue at 73.61 for 0.8 speak bu kui shi yi ge xu ',
			'say liuyue at 74.79 for 0.24 speak shi jie ',
			),
		'name'		=> 'Scene ');

$v['scene_00006'] = $v['scene_00005'];
$v['scene_00006']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00007'] = $v['scene_00005'];
$v['scene_00007']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00008'] = $v['scene_00005'];
$v['scene_00008']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00009'] = array(
		'duration'	=> 57,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 55 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_10 55 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.04 for 1.42 speak kartman chui wan niu bi zhi hou ne ',
			'say liuyue at 3.4 for 0.25 speak kail gan ',
			'say liuyue at 3.87 for 0.37 speak tan yi sheng ',
			'say liuyue at 4.96 for 2.01 speak shuo kan kan zan men zhou wei wan you xi de zhei xie ren ',
			'say liuyue at 7.97 for 0.83 speak kartman shuo bullcrap ',
			'say liuyue at 9.7 for 1.78 speak wo gan shuo zhei li mian you yi baner dou shi han guo ren ',
			'say liuyue at 12.8 for 0.35 speak bullcrap ',
			'say liuyue at 13.51 for 0.55 speak jiu shi bullshit ',
			'say liuyue at 14.86 for 0.78 speak ye jiu shi hu shuo hu che ',
			'say liuyue at 16.74 for 0.58 speak you de shi hou ',
			'say liuyue at 17.73 for 0.54 speak dan shuo krap ',
			'say liuyue at 18.56 for 0.75 speak ye ke yi biao shi zhei ge ',
			'say liuyue at 20.56 for 0.16 speak yi yang ',
			'say liuyue at 21.47 for 0.65 speak zhei li bullcrap ',
			'say liuyue at 22.49 for 1.3 speak gen ben jiu mei you ming que de yi si ',
			'say liuyue at 24.68 for 0.81 speak zhi shi ge kou tou yuer ',
			'say liuyue at 26.36 for 2.46 speak kaitman qi shi bing bu shi kan bu qi you xi li de nei xie ren ',
			'say liuyue at 29.51 for 1.57 speak huo zhe shi shuo han guo ren sha bi huo zhe zen ',
			'say liuyue at 32.31 for 0.72 speak ta jiu sui bian zhe me yi shuo ',
			'say liuyue at 33.99 for 0.26 speak zan ne ',
			'say liuyue at 34.8 for 0.51 speak ye jiu zhe me yi ting ',
			'say liuyue at 36.49 for 1.85 speak bu guo ying gai xue yi xia ai bet zhei ge duan yu ',
			'say liuyue at 39.23 for 1.16 speak biao da wo da du zen yang ',
			'say liuyue at 41.61 for 1.76 speak qi shi bing bu yi ding yao shuo zhen de yao da du ',
			'say liuyue at 44.28 for 0.78 speak zhi bu guo shi jia qiang yu ',
			'say liuyue at 46.63 for 0.51 speak ai lun puo ',
			'say liuyue at 48.08 for 0.87 speak edgar allen pou ',
			'say liuyue at 49.6 for 0.41 speak ta you yi pian xiao shuo ',
			'say liuyue at 50.23 for 0.97 speak er zhuan men jiang gui ze ',
			'say liuyue at 51.44 for 0.72 speak kou tou yuer hao da du ',
			'say liuyue at 53.43 for 1.54 speak shuo hua nei ke shi mao liang bai nian ',
			),
		'name'		=> 'Scene ');

$v['scene_00010'] = $v['scene_00009'];
$v['scene_00010']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00011'] = $v['scene_00009'];
$v['scene_00011']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00012'] = $v['scene_00009'];
$v['scene_00012']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00013'] = array(
		'duration'	=> 20,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 18 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_11 18 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.07 for 0.73 speak sdan shuo krap ',
			'say liuyue at 2.4 for 1.01 speak nei ge jia huo you lai le ',
			'say liuyue at 4.26 for 0.73 speak kail wen shi shei ',
			'say liuyue at 5.73 for 0.49 speak sdan shuo ',
			'say liuyue at 6.68 for 1.61 speak ta jiu shi nei tian ni qu shui jiao zhi hou ',
			'say liuyue at 8.78 for 0.73 speak lian sha wo men de ren ',
			'say liuyue at 10.83 for 1.68 speak xiang kip killing as zhe yang de duan yu ',
			'say liuyue at 13.03 for 1.58 speak ye zhi you zai waner you xi de shi hou cai neng shuo de chu lai ',
			'say liuyue at 15.73 for 0.97 speak kao si liu ji de tong xue ',
			'say liuyue at 17.24 for 1.4 speak nin men jiu bu yong ji zhei zhong biao da fang ',
			),
		'name'		=> 'Scene ');

$v['scene_00014'] = $v['scene_00013'];
$v['scene_00014']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00015'] = $v['scene_00013'];
$v['scene_00015']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00016'] = $v['scene_00013'];
$v['scene_00016']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00017'] = array(
		'duration'	=> 97,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 95 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_12 95 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.98 for 1.27 speak kaitman shuo gun kai sha bi ',
			'say liuyue at 3.1 for 1.21 speak zhei ju hua fei chang de jing dian ',
			'say liuyue at 4.95 for 0.44 speak wei shen me ne ',
			'say liuyue at 6.23 for 0.26 speak di yi ',
			'say liuyue at 7.31 for 0.73 speak get out of here ',
			'say liuyue at 8.61 for 0.72 speak zhe shi yi ju bi bei ',
			'say liuyue at 10.48 for 1.2 speak shuo lets get out of here ',
			'say liuyue at 12.12 for 0.62 speak shi zan zou ba ',
			'say liuyue at 13.54 for 0.87 speak yao shi dui bie ren shuo ',
			'say liuyue at 14.83 for 0.52 speak get out of here ',
			'say liuyue at 15.99 for 0.97 speak nei jiu shi gun dan ',
			'say liuyue at 17.92 for 0.57 speak fei chang bu ke qi ',
			'say liuyue at 19.47 for 1.09 speak tong yi duan yu you bitit ',
			'say liuyue at 21.15 for 0.27 speak fak off ',
			'say liuyue at 21.9 for 0.11 speak deng deng ',
			'say liuyue at 23.09 for 0.42 speak dang ran la ',
			'say liuyue at 24.28 for 1.43 speak yao shuo get de fak out of here ',
			'say liuyue at 26.11 for 0.56 speak na jiu geng jin ',
			'say liuyue at 27.21 for 0.9 speak chen le gun ni ma de dan le ',
			'say liuyue at 29.39 for 0.45 speak di er ge chu ',
			'say liuyue at 30.11 for 1.21 speak caier de di fang ji shi asshoul zhei ge ',
			'say liuyue at 32.41 for 0.35 speak ass shi ',
			'say liuyue at 32.98 for 0.2 speak pi gu ',
			'say liuyue at 33.81 for 0.3 speak houl shi dong ',
			'say liuyue at 34.89 for 0.74 speak as shi zang hua ',
			'say liuyue at 36.27 for 0.64 speak zhei ge asshoul ',
			'say liuyue at 37.57 for 0.68 speak jiu shi pi yaner a ',
			'say liuyue at 39.02 for 0.27 speak bi ass ',
			'say liuyue at 39.51 for 0.29 speak hai yao zang ',
			'say liuyue at 41.07 for 0.95 speak zui jin hao xiang liu xing ass ',
			'say liuyue at 42.25 for 0.11 speak krak ',
			'say liuyue at 43.18 for 1.19 speak zhi yi shi pi gu feng ',
			'say liuyue at 44.96 for 0.95 speak biao da cha bu duo de yi ',
			'say liuyue at 46.86 for 0.94 speak hao xiang hei yong de bi jiao duo ',
			'say liuyue at 49.33 for 0.49 speak shuo dao zheer le ',
			'say liuyue at 50.52 for 1.86 speak zan men suo xing jiu zai duo shuo yi ge ci bat ',
			'say liuyue at 53.44 for 0.72 speak bat ye shi pi gu ',
			'say liuyue at 55.14 for 0.72 speak zang hua de cheng du ',
			'say liuyue at 56.14 for 0.57 speak ass cha yi dian ',
			'say liuyue at 57.75 for 1.05 speak maikou zhaikson de bad li ',
			'say liuyue at 59.02 for 1.42 speak di yi ju jiu shi your bat is main ',
			'say liuyue at 61.38 for 1.61 speak ba qi nian shuo chu zhei ju hua ke neng xian de hen ',
			'say liuyue at 64.03 for 0.85 speak fang dao xian zai jiu tai xiao er ',
			'say liuyue at 66.59 for 1.4 speak jiu hao bi shit he krap de guan ',
			'say liuyue at 68.87 for 0.98 speak bat he ass cha bu duo ',
			'say liuyue at 70.64 for 1.37 speak ye ke yi yong bathoul biao ',
			'say liuyue at 72.3 for 0.2 speak pi yaner ',
			'say liuyue at 73.26 for 0.92 speak bu guo bu guan zen me shuo ba ',
			'say liuyue at 74.94 for 1.34 speak asshoul ye hao bathoul ye ba ',
			'say liuyue at 77.22 for 1.57 speak zhen zheng yong de shihou dou bu shi ',
			'say liuyue at 79.06 for 0.62 speak nei ge ',
			'say liuyue at 80.44 for 0.49 speak qi guan ',
			'say liuyue at 81.96 for 0.95 speak suo yi wo ren wei sha ',
			'say liuyue at 83.66 for 0.94 speak bi jiao he shi de fan yi ',
			'say liuyue at 85.42 for 0.82 speak zan men shuo sha bi ',
			'say liuyue at 86.74 for 0.59 speak ye bu shi ',
			'say liuyue at 87.6 for 0.19 speak nei ge ',
			'say liuyue at 88.07 for 0.26 speak qi guan ',
			'say liuyue at 90.23 for 1.17 speak yi ban de fan yi ze shi hun dan ',
			'say liuyue at 92.33 for 1.31 speak he ass you guan de ying yu xian xiang ',
			'say liuyue at 94.16 for 0.97 speak yi hou ying gai hai hui yu dao ',
			'say liuyue at 95.75 for 1.1 speak dao shi hou zan men zai xie shuo ',
			),
		'name'		=> 'Scene ');

$v['scene_00018'] = $v['scene_00017'];
$v['scene_00018']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00019'] = $v['scene_00017'];
$v['scene_00019']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00020'] = $v['scene_00017'];
$v['scene_00020']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00021'] = array(
		'duration'	=> 91,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 89 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_13 89 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.85 for 2.17 speak sdan shuo ta deng ji bi wo men gao duo le ',
			'say liuyue at 3.65 for 0.69 speak zhei bu gong ping a ',
			'say liuyue at 5.16 for 0.7 speak kail shuo mei shier ',
			'say liuyue at 6.58 for 2.02 speak wo men bu tong yi pi kei ta jiu bu neng sha si wo ',
			'say liuyue at 9.77 for 1.76 speak zhei shi ta shang ci shui de zao mei gan shang ',
			'say liuyue at 12.55 for 1.2 speak zhi jian bian tai jia mian ',
			'say liuyue at 14.36 for 1.77 speak yi xun lei bu ji yan er dao ling zhi shi ',
			'say liuyue at 16.37 for 0.93 speak tao chu yi ba xiao daoer ',
			'say liuyue at 17.58 for 0.85 speak jiang kenny tong si ',
			'say liuyue at 19.07 for 0.64 speak jing dian tai ci ',
			'say liuyue at 20.18 for 0.49 speak ou mai gad ',
			'say liuyue at 21.09 for 0.65 speak he kill kenny ',
			'say liuyue at 22.25 for 0.82 speak you bastard ',
			'say liuyue at 23.56 for 0.32 speak zai xian ',
			'say liuyue at 25.27 for 2.28 speak zai ju ji nan fang gong yuan de qian ji ji li ',
			'say liuyue at 28.14 for 0.83 speak kenny ji hu shi mei ',
			'say liuyue at 29.21 for 0.25 speak ji bi ',
			'say liuyue at 30.54 for 1.94 speak hou lai zhi zuo ren trey parker he matt sdoun ',
			'say liuyue at 33.16 for 1.62 speak bu xiang lao zuo mo zen me sha si kenny le ',
			'say liuyue at 35.38 for 1 speak suo yi xian zai shi bu zen me ',
			'say liuyue at 37.71 for 1.8 speak dang ran zui xin de yi ji kenny hai shi si ',
			'say liuyue at 40.35 for 2.14 speak dang shi quan shi jie po you yi bang ren zhu he le ban ',
			'say liuyue at 43.99 for 1.6 speak bastard zhe ge cier shao wei ti yi xia ',
			'say liuyue at 46.4 for 0.99 speak ta yuan yi shi si sheng ',
			'say liuyue at 48.6 for 1.09 speak qi shi ye jiu shi yi ju hen pu ',
			'say liuyue at 49.92 for 0.52 speak tong de zang hua ',
			'say liuyue at 51.58 for 4.68 speak wo ji de yi ge zai mei guo de zhong guo lao nu ren xie de yi ben shu li jiu lao chu xian zhei ge cier ',
			'say liuyue at 56.68 for 1.44 speak gu ji shi zi yi wei xian de ',
			'say liuyue at 58.43 for 0.3 speak niu bi de ',
			'say liuyue at 60.07 for 1.44 speak kartman fei chang zheng yi de gao hu ',
			'say liuyue at 62.05 for 2.3 speak ni chu le shang wang sha ren yi wai jiu mei shier gan le ma ',
			'say liuyue at 65.1 for 1.24 speak ran hou ta sa ya zi jiu pao ',
			'say liuyue at 66.74 for 1.11 speak yi bianer pao yi bianer shuo ',
			'say liuyue at 68.32 for 1.79 speak wo bu xiang zai mu di li chong xin kai shi ',
			'say liuyue at 71.31 for 1.52 speak zhei shi mo shou shi jie li de she ding ',
			'say liuyue at 73.54 for 1.55 speak bei sha si de ren hui zai mu di li ',
			'say liuyue at 76.51 for 0.57 speak zhu yi zhei li ',
			'say liuyue at 77.49 for 1.22 speak you yi ge ting you yi si de xi jie ',
			'say liuyue at 79.6 for 1.47 speak jiu shi mei ge ren shou gong ji de shi hou ',
			'say liuyue at 81.55 for 1.21 speak dou hui yong you xi li de sheng yin ',
			'say liuyue at 83.86 for 1.24 speak you qi shi kail bei sha nei dian ',
			'say liuyue at 85.8 for 1.29 speak you dianer friki gerl de gan jue ',
			'say liuyue at 88.01 for 1.9 speak bu zhi dao shi bu shi wai guo ren kou zhong de ',
			),
		'name'		=> 'Scene ');

$v['scene_00022'] = $v['scene_00021'];
$v['scene_00022']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00023'] = $v['scene_00021'];
$v['scene_00023']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00024'] = $v['scene_00021'];
$v['scene_00024']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00025'] = array(
		'duration'	=> 84,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 82 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_14 82 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.85 for 1.4 speak kartman qi de ba er ji yi shuai ',
			'say liuyue at 2.83 for 1.18 speak ma le yi ju mei guo guo ma ',
			'say liuyue at 4.4 for 1.06 speak dat son of a bitch ',
			'say liuyue at 6.17 for 0.95 speak he zhong wen guo niang yang ',
			'say liuyue at 7.35 for 0.32 speak de dui ying ',
			'say liuyue at 9.15 for 1.85 speak zhong xi wen hua si lu qi shi dou cha bu duo ',
			'say liuyue at 12.06 for 0.78 speak bie ren jiu bi jiao lan ',
			'say liuyue at 13.08 for 0.15 speak jing le ',
			'say liuyue at 14.1 for 0.43 speak kail shuo ',
			'say liuyue at 14.93 for 1 speak zhei jia huo shi ga ma de ya ',
			'say liuyue at 16.8 for 1.34 speak sdan shuo bu guan ta shi shui ',
			'say liuyue at 18.72 for 0.97 speak ta dou shi yi ge da huai dan ',
			'say liuyue at 20.94 for 1.11 speak taf zhe ge cier ben yi shi ',
			'say liuyue at 22.33 for 0.16 speak qiang ying ',
			'say liuyue at 23.23 for 0.81 speak dan shi hen duo shi hou ',
			'say liuyue at 24.73 for 1.41 speak fan yi cheng niu bi geng wei qia dang ',
			'say liuyue at 27.2 for 0.84 speak bi ru quan huang li ',
			'say liuyue at 28.59 for 1.83 speak kei jiu jiu jiu jiu de yi ju tai ci ',
			'say liuyue at 31.17 for 1.1 speak you sik yourself taf ',
			'say liuyue at 32.86 for 0.51 speak you just meik ',
			'say liuyue at 33.59 for 0.35 speak me laf ',
			'say liuyue at 35.22 for 0.52 speak shuo dao niu bi ',
			'say liuyue at 36.37 for 1.79 speak wo dui han yu de ma jie you xie you lv ',
			'say liuyue at 39.31 for 1.47 speak da jia kan mei guo dian shi ju ',
			'say liuyue at 41.19 for 0.84 speak ying gai ke yi fa xian ',
			'say liuyue at 42.63 for 0.22 speak zhei ji ',
			'say liuyue at 43.09 for 0.11 speak nian ',
			'say liuyue at 43.55 for 1.7 speak bu xiao yin de fak shit yue lai yue duo ',
			'say liuyue at 46.3 for 1.08 speak pusi ass maderfaking ',
			'say liuyue at 47.64 for 0.27 speak man tian fei ',
			'say liuyue at 48.61 for 2.69 speak shen zhi you ai fakd your mom you fatass maderfucker ',
			'say liuyue at 51.55 for 0.35 speak zhe yang de biao ',
			'say liuyue at 53.06 for 0.86 speak zhi bi zhong guo ren ',
			'say liuyue at 54.19 for 0.89 speak qian zi hao de guo ma ',
			'say liuyue at 55.67 for 0.11 speak ma ',
			'say liuyue at 56.8 for 0.59 speak fan guo lai ne ',
			'say liuyue at 58.38 for 0.79 speak han yu li wo cao ',
			'say liuyue at 59.43 for 0.39 speak bian cheng le wo ',
			'say liuyue at 60.83 for 1.22 speak niu bi bian cheng le niu cha ',
			'say liuyue at 62.78 for 1 speak chang ci yi wang shi ',
			'say liuyue at 64.26 for 0.33 speak ci zhang ',
			'say liuyue at 64.96 for 0.22 speak bi xiao a ',
			'say liuyue at 66.89 for 1.22 speak er qie wo guo zang ',
			'say liuyue at 68.43 for 0.95 speak hua da guo de di wei ',
			'say liuyue at 69.68 for 1.57 speak ben lai shi jian zhu zai fang yan de ji chu ',
			'say liuyue at 72.58 for 0.37 speak cao ni ma ',
			'say liuyue at 73.31 for 0.39 speak gan ni niang ',
			'say liuyue at 73.99 for 0.48 speak ri ni lao mu ',
			'say liuyue at 75.03 for 0.77 speak qi shi dou shi yi ge yi si ',
			'say liuyue at 76.68 for 0.97 speak xian zai tui guang pu tong hua ',
			'say liuyue at 78.28 for 1.94 speak yi jing yan ran cheng wei le zang hua ruo shi ',
			'say liuyue at 81.56 for 0.88 speak shi zai shi rang you ',
			'say liuyue at 82.73 for 0.94 speak shi zhi shi e wan ',
			),
		'name'		=> 'Scene ');

$v['scene_00026'] = $v['scene_00025'];
$v['scene_00026']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00027'] = $v['scene_00025'];
$v['scene_00027']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00028'] = $v['scene_00025'];
$v['scene_00028']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00029'] = array(
		'duration'	=> 30,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 28 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_15 28 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.03 for 0.54 speak jie guo ne ',
			'say liuyue at 2.11 for 0.92 speak zhe ge taf bad ass ',
			'say liuyue at 4.01 for 0.62 speak shun bian shuo yi ju ',
			'say liuyue at 5.25 for 2.9 speak wo bing bu ren wei zhei ge he chang jian ci zu big bad wolf ',
			'say liuyue at 8.54 for 1.05 speak da huai lang you shen me guan ',
			'say liuyue at 10.64 for 1.45 speak trey parker xin shou nian lai de yi ge cier ',
			'say liuyue at 12.9 for 1.34 speak zan men fan bu zhao shang gang shang xian ',
			'say liuyue at 15.13 for 0.85 speak zhei ge bian tai jia mian ',
			'say liuyue at 16.5 for 2.29 speak guo ran shi yi wei bian tai shu shu lao zhai nan ',
			'say liuyue at 19.84 for 1.82 speak gu ji kan dao zhei li tu xie de ren bu shao ',
			'say liuyue at 22.21 for 0.91 speak zhai cheng zhei ge yang zi ',
			'say liuyue at 23.42 for 0.49 speak ye bu rong yi ',
			'say liuyue at 24.79 for 0.69 speak zan men zai kan yi bian ',
			'say liuyue at 26.01 for 0.65 speak da jia zi xi ting ',
			'say liuyue at 27.35 for 0.61 speak xi wang zhei ci ',
			'say liuyue at 28.4 for 1.58 speak neng gen shang zhu jue men shuo de hua ',
			),
		'name'		=> 'Scene ');

$v['scene_00030'] = $v['scene_00029'];
$v['scene_00030']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00031'] = $v['scene_00029'];
$v['scene_00031']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00032'] = $v['scene_00029'];
$v['scene_00032']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00033'] = array(
		'duration'	=> 21,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 19 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_16 19 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 0.99 for 2.25 speak xia mian de qing jie fa sheng zai blizzerd zong bu ',
			'say liuyue at 4.11 for 0.36 speak blizzerd ',
			'say liuyue at 5.07 for 0.59 speak yi worcraft ',
			'say liuyue at 6.33 for 0.36 speak diablo ',
			'say liuyue at 7.45 for 0.58 speak he sdarcraft ',
			'say liuyue at 8.58 for 1.52 speak san da xi lie wen ming yu shi ',
			'say liuyue at 10.79 for 1.62 speak ke wei chu shou ji shi jing pin ',
			'say liuyue at 13.71 for 1.39 speak ju shuo dong hua li de chang jing ',
			'say liuyue at 15.68 for 3.14 speak shi can kao zhen zheng de blizzerd zong bi li de chen she zhi zuo de ',
			'say liuyue at 19.78 for 0.79 speak zan men lai kan zhei duan ying ',
			),
		'name'		=> 'Scene ');

$v['scene_00034'] = $v['scene_00033'];
$v['scene_00034']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00035'] = $v['scene_00033'];
$v['scene_00035']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00036'] = $v['scene_00033'];
$v['scene_00036']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00037'] = array(
		'duration'	=> 24,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 22 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_17 22 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.1 for 1.85 speak ke fu shuo zhei shi world of worcraft ',
			'say liuyue at 3.24 for 0.55 speak zhi chi re xian ',
			'say liuyue at 4.69 for 0.89 speak sdan sheng qi de shuo ',
			'say liuyue at 6.27 for 2.14 speak wo men mai le ni men de you xi ran hou shang xian waner ',
			'say liuyue at 9 for 1.33 speak dan shi mei ci wo men yi deng lu ',
			'say liuyue at 10.84 for 1.55 speak zong you yi ge ren guo lai ba wo men sha le ',
			'say liuyue at 13.17 for 1.1 speak ke fu shuo nei bu ying gai a ',
			'say liuyue at 15.04 for 1.2 speak wo men she ji de you xi gui ze ',
			'say liuyue at 16.75 for 2.44 speak shi pi kei zhi qian shuang fang bi xu dou tong yi jue dou ',
			'say liuyue at 19.93 for 0.53 speak zhu yi zhei li ',
			'say liuyue at 21 for 0.39 speak kills as ',
			'say liuyue at 21.96 for 1.45 speak ye shi dian xing de wang you waner jia de yong ',
			),
		'name'		=> 'Scene ');

$v['scene_00038'] = $v['scene_00037'];
$v['scene_00038']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00039'] = $v['scene_00037'];
$v['scene_00039']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00040'] = $v['scene_00037'];
$v['scene_00040']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00041'] = array(
		'duration'	=> 72,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			'blend item_oneman_light at 70 for 1 from 0 to 100 ',
			'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_18 70 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.09 for 0.72 speak sdan shuo shi a ',
			'say liuyue at 2.51 for 1.7 speak ke nei jia huo jiu zhi jie ba wo men sha le ',
			'say liuyue at 5.07 for 0.5 speak zhe ge das it ',
			'say liuyue at 6.23 for 2.33 speak jiu shi sheng lve qian wen de keims in and kills as ',
			'say liuyue at 9.75 for 0.81 speak kartman bu chong shuo ',
			'say liuyue at 10.88 for 1.13 speak ta shi ge zao tian qian de hun dan ',
			'say liuyue at 13.09 for 1.22 speak xiang gaddamned zhei zhong cu hua ',
			'say liuyue at 14.93 for 0.87 speak he xi fang shi jie de ',
			'say liuyue at 16.08 for 0.92 speak zong jiao bei jing you guan ',
			'say liuyue at 17.87 for 1.45 speak damn de yuan yi jiu shi bei zu zhou de ',
			'say liuyue at 20.25 for 0.61 speak gaddamn ne ',
			'say liuyue at 21.54 for 1.03 speak jiushi bei shang ci zu zhou de ',
			'say liuyue at 23.58 for 0.91 speak zhei ge he zhong wen de ',
			'say liuyue at 24.71 for 0.5 speak tian sha de ',
			'say liuyue at 25.66 for 0.57 speak zao tian qian de ',
			'say liuyue at 26.73 for 0.86 speak ye you xiang si zhi chu ',
			'say liuyue at 28.31 for 1.51 speak suo yi wo shuo zhei ge gu jin zhong wai ',
			'say liuyue at 30.38 for 1.27 speak da jia de si lu dou cha bu duo ',
			'say liuyue at 32.57 for 0.84 speak bathoul qian mian shuo guo ',
			'say liuyue at 34.57 for 1.23 speak ke fu shuo nei ke qi guai le ',
			'say liuyue at 36.63 for 1.37 speak ran hou ta xiao sheng dui zhu guan shuo ',
			'say liuyue at 38.54 for 2.61 speak yue lai yue duo de ren da dian hua shuo ta men de ren wu bei sha le ',
			'say liuyue at 41.95 for 0.88 speak da jia ke yi kan chu lai ',
			'say liuyue at 43.46 for 2.11 speak wan jia he zheng chang ren de xin tai ming xian bu tong ',
			'say liuyue at 46.58 for 1.3 speak wan jia shuo dao zi ji de jue se ',
			'say liuyue at 48.51 for 1.36 speak dou shi zhi jie yong wo men lai da ti ',
			'say liuyue at 50.27 for 0.32 speak bi ru ',
			'say liuyue at 51.04 for 0.85 speak wo men bei sha le hao ji ',
			'say liuyue at 52.71 for 0.81 speak zheng chang ren jiu bu hui zhe me ',
			'say liuyue at 55.05 for 1.67 speak ran hou ke fu xiao jie gao su sdan ta men ',
			'say liuyue at 57.34 for 1.29 speak wo men yi ding zhao dao nei ge wan jia ',
			'say liuyue at 59.14 for 1.18 speak ran hou ba ta de zhang hao feng le ',
			'say liuyue at 61.23 for 0.92 speak zhe ge ban shi jin ling ',
			'say liuyue at 62.57 for 0.69 speak jin zhi de yi si ',
			'say liuyue at 64.05 for 1.77 speak zai wang luo li yi ban dou dai you yong jiu xing ',
			'say liuyue at 66.47 for 0.99 speak bi ru feng suo zhang haoer ',
			'say liuyue at 67.75 for 0.33 speak ai pi deng ',
			'say liuyue at 69.07 for 0.97 speak ran hou ta xiao sheng shuo ',
			'say liuyue at 70.64 for 1.26 speak zui hao qu gao su lou shang nei bang ren ',
			),
		'name'		=> 'Scene ');

$v['scene_00042'] = $v['scene_00041'];
$v['scene_00042']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00043'] = $v['scene_00041'];
$v['scene_00043']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00044'] = $v['scene_00041'];
$v['scene_00044']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

//	----------------------------------------------------

$v['scene_00045'] = array(
		'duration'	=> 41,
		'bg_color'	=> $v['color_blue'],
		'camera'	=> array(
			array(0, 0, 0.14, 0.85, 1.8, 9999),
			array(0, 0, 0.14, 0.85, 1.8, 0),
			),
		'object'	=> array(
			'room_oneman_hall',
			'liuyue',
			//	'slide_oneman',
			'item_oneman_light',
			'furniture_oneman_platform',
			),
		'script'	=> array(
			'set liuyue as kid at 0.31 0.25 size 0.4 ',
			//	'blend item_oneman_light at 1 for 1 from 100 to 0 ',
			//	'blend item_oneman_light at 39 for 1 from 0 to 100 ',
			//	'sub slide_oneman at 0 for 999 with 3 item null 2 item/slide/oneman_001_09 39 null 999 ',
			//	speech generated by ogg2txt
			'say liuyue at 1.02 for 0.38 speak zhei li ',
			'say liuyue at 2 for 2.82 speak ke fu xiao jie zai ci rang wo men tie jin le mei guo ren de sheng huo ',
			'say liuyue at 5.69 for 0.28 speak di yi ',
			'say liuyue at 6.53 for 1.78 speak mei guo ke fu ye hu nong gu ke ',
			'say liuyue at 9.1 for 0.22 speak di er ',
			'say liuyue at 9.9 for 1.98 speak mei guo lao zi guan xi da jia ye kan de hen ',
			'say liuyue at 13.08 for 2.54 speak xiang ke fu shuo dao lao ban jiu shi lou shang nei bang ren ',
			'say liuyue at 16.29 for 1.92 speak yi ting jiu zhi dao da huo bu shi yi lei ren ',
			'say liuyue at 19.32 for 2.02 speak wo men lao shi shang ke de shi hou shuo guo yi ge xiao hua ',
			'say liuyue at 22.16 for 2.08 speak shuo you ren gong si li lao ban fa le yi feng you jian ',
			'say liuyue at 25.09 for 0.63 speak nei rong shi ',
			'say liuyue at 26.12 for 2.18 speak rong yi bei lao ban chao diao de wu zhong yuan gong ',
			'say liuyue at 29.04 for 2.15 speak ran hou yuan gong zi ji jiu kai shi nei bu fa you jian ',
			'say liuyue at 31.79 for 0.58 speak nei rong shi ',
			'say liuyue at 32.87 for 1.88 speak rong yi bei yuan gong chao diao de wu zhong lao ban ',
			'say liuyue at 35.63 for 1.03 speak deng wo zhang da zhi hou ',
			'say liuyue at 37.13 for 0.95 speak da gai ye hui peng dao zhei zhong ',
			'say liuyue at 38.32 for 0.19 speak shier ',
			'say liuyue at 39.43 for 1.63 speak zan men zai kan yi bian mei guo ke fu de hua ',
			),
		'name'		=> 'Scene ');

$v['scene_00046'] = $v['scene_00045'];
$v['scene_00046']['camera'] = array(
			array(0, 0, 0.5, 0.5, 1, 9999),
			array(0, 0, 0.5, 0.5, 1, 0));

$v['scene_00047'] = $v['scene_00045'];
$v['scene_00047']['camera'] = array(
			array(0, 0, 0.7, 0.5, 1.5, 9999),
			array(0, 0, 0.7, 0.5, 1.5, 0));

$v['scene_00048'] = $v['scene_00045'];
$v['scene_00048']['camera'] = array(
			array(0, 0, 0.75, 0.6, 1.8, 9999),
			array(0, 0, 0.75, 0.6, 1.8, 0));

?>
